# Libraries

In [1]:
! pip install  transformers
! pip install sentencepiece
#SentencePiece is a library for tokenization and detokenization that is commonly used in natural language processing (NLP) and machine learning tasks.

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.11.17)
Collecting sentencepiece
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.5 MB/s eta 0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.99

# Text-classification

In [2]:
# ! pip install  transformers

from transformers import pipeline
import pandas as pd

text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon provide """

In [3]:

classifier = pipeline("text-classification" , model = 'distilbert-base-uncased-finetuned-sst-2-english' )
# Pipeline(name_of_task  , name of the model from hugging face)
# https://huggingface.co/models

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [4]:

outputs = classifier(text)
pd. DataFrame(outputs)

      label     score
0  NEGATIVE  0.999357

In [5]:
# Get the model's configuration
model_config = classifier.model.config

# Get the labels used by the model
labels = model_config.id2label

# Print the labels
print(labels)

{0: 'NEGATIVE', 1: 'POSITIVE'}

#summary_text

In [10]:
# ! pip install  transformers
from transformers import pipeline
import pandas as pd

text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon Egypt provide """

In [11]:
summarizer = pipeline("summarization"  , model  = "sshleifer/distilbart-cnn-12-6")
outputs = summarizer(text, max_length=75, clean_up_tokenization_spaces=True)
print(outputs[0]['summary_text' ])

config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

 When this air fryer works it is great but upon delivery the first day it unfortunately broke. I selected the return and replace option thinking that when the item was collected I would have a new one delivered. The day for collection came and went with no update or explanation as to why the collection was not completed. The airfryer worked well for a few

# named entity recognition eith pipeline

In [6]:
from transformers import pipeline
import pandas as pd

text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon Egypt provide """

In [7]:
# if we didn't spiecify model name it will use the default model for the task
ner_tagger = pipeline("ner",model = "dbmdz/bert-large-cased-finetuned-conll03-english" ,aggregation_strategy="simple" )
outputs = ner_tagger(text)
out = pd.DataFrame(outputs)
out.head()

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

  entity_group     score    word  start   end
0          ORG  0.998724  Amazon    368   374
1          ORG  0.996317  Amazon   1284  1290
2          LOC  0.928347   Egypt   1291  1296

1- The aggregation_strategy parameter is used to determine how overlapping entities are aggregated when extracting named entities from the input text.

2- The aggregation_strategy="simple" means that a simple strategy will be used to handle overlapping entities. When multiple entities overlap in the output, this strategy will likely keep all of them in the result, and you'll get a list of entities for each token.

3- For instance, if the model identifies entities like "ORG" (organization) and "LOC" (location) in overlapping spans, the simple strategy might include both entities in the result, even if they overlap.

4- Other possible values for the aggregation_strategy parameter include:

"first": Keep only the first identified entity when there is an overlap.
"mean": Compute the mean of the scores for the overlapping entities.
"max": Keep the entity with the maximum score when there is an overlap.
The appropriate choice of the aggregation strategy depends on your specific use case and how you want to handle overlapping entities in the NER results. The default value is typically "first". The choice of strategy can affect the precision and recall of the NER system.

### QA with pipeline

In [15]:
# ! pip install  transformers
from transformers import pipeline
import pandas as pd

text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option thinking that when the item was collected I would have a new one delivered.
This was sadly not the case and the day for collection came and went with no update or explanation as to why the collection was not completed.
I contacted Amazon and after going through a few circles trying to actually speak to someone I was informed that the driver couldn't find me.
This I can understand but not them not trying to contact me to help them locate my property.
Finally after three weeks of collection and delivery pending on my item the same item was returned to me "repaired".
This was not the option that I selected as if something is faulty I do not want it back,
I want a new non faulty item sent to me. The airfryer worked well for a few days then the light went out and then it stopped working altogether.
I am now in the pending stage again but this time for a full refund.
The reason I sent it back in the beginning was to avoid it breaking again as I knew it would but here we are anyway.
I just hope I am not waiting an age for the refund to come through so I can purchase an airfryer
elsewhere with a better level of customer service than Amazon Egypt provide """

In [16]:
reader = pipeline("question-answering" ,  model = "distilbert-base-cased-distilled-squad" )

In [17]:
question = "What does the customer want?"
outputs = reader(question=question,context=text)
pd. DataFrame([outputs])

# score: The confidence score associated with the extracted answer. In this case, the score is 0.33468106389045715.
# start: The character index in the original text where the answer starts. In this case, the answer starts at index 807.
# end: The character index in the original text where the answer ends. In this case, the answer ends at index 839.
# answer: The extracted answer from the context.

      score  start  end                            answer
0  0.334681    807  839  a new non faulty item sent to me

In [18]:
outputs

{'score': 0.33468106389045715,
 'start': 807,
 'end': 839,
 'answer': 'a new non faulty item sent to me'}

In [19]:
question = "did  the customer deliver new air fyer or not ?"
outputs = reader(question=question,context=text)
pd. DataFrame([outputs])

      score  start  end                       answer
0  0.001347    212  239  This was sadly not the case

In [20]:
outputs

{'score': 0.0013465078081935644,
 'start': 212,
 'end': 239,
 'answer': 'This was sadly not the case'}

#translation_text

In [25]:
# ! pip install  transformers
from transformers import pipeline
import pandas as pd

text = """When this air fryer works it is great but upon delivery the first day it unfortunately broke.
I selected the return and replace option. I thougth that when the item was collected I would have a new one delivered, but until now
there is no update or explanation why the collection was not completed. """

In [26]:
translator = pipeline("translation_en_to_ar" ,model="marefa-nlp/marefa-mt-en-ar" )

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:197: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

In [27]:
outputs = translator(text, clean_up_tokenization_spaces=True, min_length= 65)
print(outputs[0]['translation_text' ])

# clean_up_tokenization_spaces=True: When set to True, this parameter instructs the translation pipeline to clean up tokenization spaces.
# Tokenization is the process of breaking a text into individual units, usually words or subwords.
# Sometimes, there might be extra spaces introduced during tokenization.
# Setting clean_up_tokenization_spaces=True helps to remove or clean up these additional spaces, ensuring a more coherent translation.

#-------------------------
# min_length=65: This parameter sets a minimum length for the output translation. In this case, it is set to 65.
# If the length of the translated text is less than 65 characters, the pipeline may adjust or generate additional content to meet this minimum length requirement.

وعندما تعمل هذه المقلية الهوائية فإنها عظيمة ولكن عند التسليم في اليوم الأول الذي تكسرت فيه لسوء الحظ.اخترت خيار العائد واستبداله.. كنت أويگث أنه عند جمع الصنف سيكون لدي صنف جديد تم تسليمه، ولكن حتى الآن لا يوجد تحديث أو تفسير لماذا لم يتم الانتهاء من المجموعة.

#generated_text

In [30]:

generator = pipeline('text-generation', model='gpt2-medium')

In [29]:
prompt = "Dear client , we are sorry to hear that your item has a problem "

outputs = generator(prompt, max_length=50 )
print(outputs[0]['generated_text' ])


# what is the meaning of prompt ?
# In the context of natural language processing and machine learning, a "prompt" refers to the input or query given to a model, typically in the form of text,
# to generate a response or make predictions. The prompt is the information or question that you provide to the model to elicit a desired output.

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Dear client , we are sorry to hear that your item has a problem  and we assure you that we are in contact with you today to resolve your problem. Please refer to the troubleshooting section for further details regarding your situation. Our customer service